# Generated by Django 3.2.9 on 2021-11-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rath', '0003_auto_20211130_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.ImageField(blank=True, upload_to='items/image'),
        ),
    ]
