# Generated by Django 3.2 on 2021-09-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rath', '0003_alter_menu_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='alcohol',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='egg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='fish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='glutenfree',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='halal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='kosher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='organic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='peanut',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='section',
            field=models.CharField(choices=[('own_pizza', 'Create Your Own Pizza'), ('8_pizza', '8 Inch Specialty Pizza'), ('12_pizza', '12 Inch Thin Crust Specialty Pizza'), ('14_pizza', '14 Inch Specialty Pizza'), ('10_pizza', '10 Inch Gluten Free Specialty Pizza'), ('wing', 'Wings & Bites'), ('vegan', 'Vegan Variations'), ('bread_stick', 'Cheesy Bread Sticks'), ('healthy', 'Healthier Options'), ('sweet', 'Sweet Creations'), ('beverage', 'Beverages'), ('fryer', 'Out of the Fryer'), ('grill', 'Out of the Grill'), ('flatbread', 'Flatbread'), ('other', 'Others')], default='other', max_length=15),
        ),
        migrations.AddField(
            model_name='menu',
            name='shellfish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='soy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='treenut',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='vegetarian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='wheat',
            field=models.BooleanField(default=False),
        ),
    ]
