# Generated by Django 3.2.9 on 2021-12-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rath', '0005_itemattribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemattribute',
            name='selected',
            field=models.BooleanField(default=True),
        ),
    ]
