# Generated by Django 3.2.9 on 2021-11-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rath', '0005_auto_20211126_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('menu', models.ManyToManyField(related_name='section_items', to='rath.Menu')),
            ],
        ),
    ]
