# Generated by Django 3.2.9 on 2021-12-01 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rath', '0006_itemattribute_selected'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet_name', models.CharField(max_length=255)),
                ('diet_description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='diet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rath.diettype'),
        ),
    ]
