# Generated by Django 3.2.9 on 2021-12-01 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rath', '0007_auto_20211201_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemattribute',
            name='diet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rath.diettype'),
        ),
        migrations.AlterField(
            model_name='itemattribute',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
