# Generated by Django 3.2.9 on 2021-12-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rath', '0008_auto_20211201_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='diettype',
            name='display_name_css_bg',
            field=models.CharField(default='green_bg', max_length=20),
        ),
    ]
