# Generated by Django 3.2.9 on 2021-12-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rath', '0010_alter_item_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemattribute',
            name='extra_cost',
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
            preserve_default=False,
        ),
    ]
