# Generated by Django 3.2.9 on 2021-12-01 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('order', '0002_auto_20211130_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='session',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sessions.session'),
            preserve_default=False,
        ),
    ]
